### ISSUE TITLE
Charging status

### ISSUE THREAD

**Issue by Nastras** [YinHangCode/homebridge-mi-robot_vacuum#2]
Hi, is it planned to add a Charging status in future?

**Comment by YinHangCode** [comment]
Charging status is already exists now version.

![img_1959](https://user-images.githubusercontent.com/15974677/30509473-064f2ea0-9ae4-11e7-913f-61d5e3e43268.PNG)

**Comment by Nastras** [comment]
It is only displayed in the Apple HomeApp, in the Elgato Eve app and other HomeKit apps is no battery status displayed?

![fullsizerender](https://user-images.githubusercontent.com/27686185/30512838-53f10188-9af8-11e7-8fd3-c0dc2e013bcd.jpg)


Additionally, the following error messages appear in the log file:

Sep 16 15:54:03 Homebridge homebridge [7165]: [2017-9-16 15:54:03] [MiRobotVacuumPlatform] [MiRobotVacuumPlatform] [ERROR] RobotVacuumFanAccessory - Battery - getLevel Error: Error: Call to device timed out

Sep 16 15:54:09 Homebridge homebridge [7165]: [2017-9-16 15:54:09] [MiRobotVacuumPlatform] [MiRobotVacuumPlatform] [ERROR] RobotVacuumFanAccessory - On - getOn Error: Error: Call to device timed out

**Comment by Nastras** [comment]
I use node 8.4.0, Homebridge 0.4.28 and npm 5.4.2
