### ISSUE TITLE
Update to 0.0.3

### ISSUE THREAD

**Issue by Nastras** [YinHangCode/homebridge-mi-robot_vacuum#4]
Hello, the update to the current version of your plugin is not working. I get the following message
![18943b2e-01d3-4aa3-a093-8441216194a8](https://user-images.githubusercontent.com/27686185/32977450-c4827a74-cc2d-11e7-9a66-5c3a1695ab3e.jpeg)

**Comment by YinHangCode** [comment]
wait a minute. I haven't publish to npm.

**Comment by Nastras** [comment]
Thanks for you quick answer👌
