### ISSUE TITLE
Slider in 4 steps

### ISSUE THREAD

**Issue by Nastras** [YinHangCode/homebridge-mi-robot_vacuum#7]
Hello, is it possible that you change slider for the stages in 4 steps 1-4?
I think that would be better to adjust as before in percent 0-100.

**Comment by YinHangCode** [comment]
In fact, the value of the wind level is 0-100， but here are only 4 level in MiHome app.

**Comment by Nastras** [comment]
Does that mean you can switch the slider from percent to 4 levels?

Slider 1 - 4 level instead of 0 - 100 percent?

For every Stage one Step in the Slider, i hope you now what i mean?

**Comment by YinHangCode** [comment]
in MiHome app, set Quiet(level 1) send to device 38, Balanced(level 2) send 60, Turbo(level 3) send 77, Max Speed(level 4) send 90.

**Comment by YinHangCode** [comment]
in this plugin, set level 1-89 send to device 1-89, set 90-100 send 90.

**Comment by YinHangCode** [comment]
The above refers to MiRobotVacuum, not MiRobotVacuum2.

**Comment by Nastras** [comment]
Yes, I also understood that the percentage in the HomeKit App Slider displays the levels of the cleaner.

My suggestion is to adjust the display of the slider in the HomeKit app. With the slider only four stages are to be indicated like here on the picture.

I think it is much clearer.

![ec5c4d16-d1c6-4b7f-a26d-bbe8b47899fa](https://user-images.githubusercontent.com/27686185/34650226-bd83abaa-f3bd-11e7-8943-263c05fddf94.jpeg)

**Comment by Nastras** [comment]
Look here, that's also a very good idea with the break switch. Would be in your plugin synonymous very good.

https://github.com/seikan/homebridge-xiaomi-mi-robot-vacuum/issues/12

**Comment by Nastras** [comment]
Hello, I wanted to ask how the chances are that you take the Pause switch with in your plugin?

What do you think about the idea with the slider in 4 stages, is that even possible?
